/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Beans.Usuario;
import Controlador.ControladorActualizar;
import Controlador.ControladorUpdate;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Sebi
 */
public class ActualizarUsuario extends javax.swing.JFrame {
     private ControladorActualizar controladorActualizar;   
     private String usuario1;
     private ControladorUpdate controladorUpdate;
     
    public ActualizarUsuario(ArrayList<Usuario> usuarios) {
        initComponents();
        controladorActualizar= new ControladorActualizar();
        //cargarUsuariosEnComboBox(usuarios); // Método para cargar usuarios
        this.setVisible(true);
        this.setSize(1200, 700);
        this.setLocationRelativeTo(null);  
        this.dispose();
         
      cargarUsuariosEnComboBox(usuarios);
        
    }
    
    private void cargarUsuariosEnComboBox(ArrayList<Usuario> usuarios) {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        controladorUpdate= new ControladorUpdate();
        // Agregar los objetos Usuario al modelo del comboBox
        for (Usuario usuario : usuarios) {
            comboBoxModel.addElement(usuario.getUsuario());
        }

        // Asignar el modelo al comboBox
        JCombobox1.setModel(comboBoxModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JCombobox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizarllados (1).jpg"))); // NOI18N
        jLabel4.setText("ACTUALIZATE MAQUINA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 120, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 150, 40));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        JCombobox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCombobox1ItemStateChanged(evt);
            }
        });
        JCombobox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCombobox1MouseClicked(evt);
            }
        });
        JCombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCombobox1ActionPerformed(evt);
            }
        });
        JCombobox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JCombobox1PropertyChange(evt);
            }
        });
        jPanel1.add(JCombobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 490, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("ACTUALIZATE MAQUINA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 640, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizarllados (1).jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -14, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
    String contraseña = jTextField2.getText();
    String correo = jTextField1.getText(); 
    
         try {    
             controladorUpdate.UpdateUsuario(usuario1, contraseña, correo);
         } catch (SQLException ex) {
             Logger.getLogger(ActualizarUsuario.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inicio pantalla = new Inicio();
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JCombobox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCombobox1MouseClicked
        
       JComboBox combo = ((JComboBox)evt.getSource());
       
        System.out.println(combo.getSelectedItem().toString());   // TODO add your handling code here:
    }//GEN-LAST:event_JCombobox1MouseClicked

    private void JCombobox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JCombobox1PropertyChange
             // TODO add your handling code here:
            
    }//GEN-LAST:event_JCombobox1PropertyChange

    private void JCombobox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCombobox1ItemStateChanged
            // TODO add your handling code here:
    }//GEN-LAST:event_JCombobox1ItemStateChanged

    private void JCombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCombobox1ActionPerformed
        // TODO add your handling code here:
        JComboBox combo = ((JComboBox)evt.getSource());
       
        usuario1 = combo.getSelectedItem().toString();
    }//GEN-LAST:event_JCombobox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JCombobox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
