/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Beans.Jugador;

/**
 *
 * @author Sebi
 */
public class Sobres extends javax.swing.JFrame {
public void mostrar() {
        this.setVisible(true); // Hace visible la ventana del menú
    }
    /**
     * Creates new form Sobres
     */
    public Sobres(Jugador jugador) {
        initComponents();
        
        this.setVisible(true);
        this.setSize(1200, 700);
        this.setLocationRelativeTo(null);
        
        int valoracion = jugador.getValoracion(); // Suponiendo que jugador.getValoracion() devuelve un int
String valoracionString = String.valueOf(valoracion);
// Alternativamente: String valoracionString = "" + valoracion;

        labelName.setText(jugador.getNombre());
        labelApellido.setText(jugador.getApellido());
        labelValoracion.setText(valoracionString);
        labelnombreequipo.setText(jugador.getNombre_Equipo());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelValoracion = new javax.swing.JLabel();
        labelnombreequipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Footbal_Stadium_Lawn_543801_3840.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 73, 103, 35));

        labelName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 150, 50));

        labelApellido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 150, 60));

        labelValoracion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(labelValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 80, 50));

        labelnombreequipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(labelnombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 190, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WEB-RARE-GOLD-T23 (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 420, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Footbal_Stadium_Lawn_543801_3840.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Menu pantalla = new Menu();
       pantalla.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelValoracion;
    private javax.swing.JLabel labelnombreequipo;
    // End of variables declaration//GEN-END:variables
}
